homework number 12
vaasilik/cypress-test pull request #1
Opened 2023-11-05 18:05 UTC by vaasilik

changed config for link 
added 1 folder 2-Locators-Actions
added 3 test cases

2023-11-05 23:11 UTC, landriiuk requested changes
Added commands needed to improve your code
Pls check them

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/forms-layouts.cy.js
a good approach to use within here!
Pls, on step about POM don't forget to delete this comments

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/forms-layouts.cy.js
> +describe("Тест 3", () => {
```suggestion
describe("Verify layouts page", () => {
```

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/forms-layouts.cy.js
> +    it("Сторінка /pages/forms/layouts", () => {
Pls change test name to english

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/layout.cy.js
> +    it("Сторінка /pages/layout/stepper", () => {
description and file name should be written in English

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/modal-overlays.cy.js
> +    it("Сторінка /pages/modal-overlays/dialog", () => {
description and file name should be written in English

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/layout.cy.js
> +        cy.get("body > ngx-app > ngx-pages > ngx-one-column-layout > nb-layout > div > div > div > div > div > nb-layout-column > ngx-components > ngx-stepper > nb-card > nb-card-body > nb-stepper >
there is a better selector for it : 
```suggestion
        cy.get("h3:eq(0)").click();
```

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/layout.cy.js
> +      }
```suggestion
      function checkStepText(stepText) {
        cy.get(".step-content").should("contain", stepText);
        stepText === "Step content #4"
        ?"Skip"
       : cy.get("h3:eq(0)").click();
      }
```

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/layout.cy.js
> +      cy.get(".step-content").should("contain", "Step content #4");
you can add additional verification into your checkStepText() method.  Added example 
```suggestion
      checkStepText("Step content #4");
```

2023-11-05 23:11 UTC, landriiuk commented on cypress/e2e/2-Locators-Actions/modal-overlays.cy.js
> +      cy.get("body > ngx-app > ngx-pages > ngx-one-column-layout > nb-layout > div.scrollable-container > div > div > div > div > nb-layout-column > ngx-modal-overlays > ngx-dialog > div > div:nth-ch
you can use here 
button:contains("Enter Name")
or cy.contains("Enter Name")

2023-11-06 07:34 UTC, vaasilik commented on cypress/e2e/2-Locators-Actions/layout.cy.js
> +        cy.get("body > ngx-app > ngx-pages > ngx-one-column-layout > nb-layout > div > div > div > div > div > nb-layout-column > ngx-components > ngx-stepper > nb-card > nb-card-body > nb-stepper >
для цього тесту в мене селектор, який ти вказала - не працює
і відповідно всі інші зміни, додані до цього тесту - фейляться

2023-11-06 07:48 UTC, closed without merging